version: "3.9"

services:
  storage_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage_service
    ports:
      - "8081:8081"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    restart: always

  cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel
    command: tunnel --no-autoupdate run --token eyJhIjoiYzJmMGJhZTM0Y2QzNTliNzlkNTViNzUwOTA0YmExZjQiLCJ0IjoiMjEzMzI4YmYtNGY2Mi00OWUzLTkzYmUtNGVhMDBiM2IyNjFkIiwicyI6IlpqVmtZbUk0TlRRdE16VXdNUzAwWm1JekxXRmlZekV0WWpGaFlURmlNalExWkRjNSJ9
    depends_on:
      - storage_service
    restart: always